spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sims?charcterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: taleyoung
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

debug: true
